/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VongChanRouteImport } from './routes/vong-chan'
import { Route as MoPhongRouteImport } from './routes/mo-phong'
import { Route as KhamBenhRouteImport } from './routes/kham-benh'
import { Route as KeDonRouteImport } from './routes/ke-don'
import { Route as DuongSinhRouteImport } from './routes/duong-sinh'
import { Route as CongNgheRouteImport } from './routes/cong-nghe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DinhDuongIndexRouteImport } from './routes/dinh-duong.index'
import { Route as DinhDuongBenhAnRouteImport } from './routes/dinh-duong.benh-an'
import { Route as DinhDuongTemplateSlugRouteImport } from './routes/dinh-duong.template.$slug'

const VongChanRoute = VongChanRouteImport.update({
  id: '/vong-chan',
  path: '/vong-chan',
  getParentRoute: () => rootRouteImport,
} as any)
const MoPhongRoute = MoPhongRouteImport.update({
  id: '/mo-phong',
  path: '/mo-phong',
  getParentRoute: () => rootRouteImport,
} as any)
const KhamBenhRoute = KhamBenhRouteImport.update({
  id: '/kham-benh',
  path: '/kham-benh',
  getParentRoute: () => rootRouteImport,
} as any)
const KeDonRoute = KeDonRouteImport.update({
  id: '/ke-don',
  path: '/ke-don',
  getParentRoute: () => rootRouteImport,
} as any)
const DuongSinhRoute = DuongSinhRouteImport.update({
  id: '/duong-sinh',
  path: '/duong-sinh',
  getParentRoute: () => rootRouteImport,
} as any)
const CongNgheRoute = CongNgheRouteImport.update({
  id: '/cong-nghe',
  path: '/cong-nghe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DinhDuongIndexRoute = DinhDuongIndexRouteImport.update({
  id: '/dinh-duong/',
  path: '/dinh-duong/',
  getParentRoute: () => rootRouteImport,
} as any)
const DinhDuongBenhAnRoute = DinhDuongBenhAnRouteImport.update({
  id: '/dinh-duong/benh-an',
  path: '/dinh-duong/benh-an',
  getParentRoute: () => rootRouteImport,
} as any)
const DinhDuongTemplateSlugRoute = DinhDuongTemplateSlugRouteImport.update({
  id: '/dinh-duong/template/$slug',
  path: '/dinh-duong/template/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cong-nghe': typeof CongNgheRoute
  '/duong-sinh': typeof DuongSinhRoute
  '/ke-don': typeof KeDonRoute
  '/kham-benh': typeof KhamBenhRoute
  '/mo-phong': typeof MoPhongRoute
  '/vong-chan': typeof VongChanRoute
  '/dinh-duong/benh-an': typeof DinhDuongBenhAnRoute
  '/dinh-duong/': typeof DinhDuongIndexRoute
  '/dinh-duong/template/$slug': typeof DinhDuongTemplateSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cong-nghe': typeof CongNgheRoute
  '/duong-sinh': typeof DuongSinhRoute
  '/ke-don': typeof KeDonRoute
  '/kham-benh': typeof KhamBenhRoute
  '/mo-phong': typeof MoPhongRoute
  '/vong-chan': typeof VongChanRoute
  '/dinh-duong/benh-an': typeof DinhDuongBenhAnRoute
  '/dinh-duong': typeof DinhDuongIndexRoute
  '/dinh-duong/template/$slug': typeof DinhDuongTemplateSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cong-nghe': typeof CongNgheRoute
  '/duong-sinh': typeof DuongSinhRoute
  '/ke-don': typeof KeDonRoute
  '/kham-benh': typeof KhamBenhRoute
  '/mo-phong': typeof MoPhongRoute
  '/vong-chan': typeof VongChanRoute
  '/dinh-duong/benh-an': typeof DinhDuongBenhAnRoute
  '/dinh-duong/': typeof DinhDuongIndexRoute
  '/dinh-duong/template/$slug': typeof DinhDuongTemplateSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cong-nghe'
    | '/duong-sinh'
    | '/ke-don'
    | '/kham-benh'
    | '/mo-phong'
    | '/vong-chan'
    | '/dinh-duong/benh-an'
    | '/dinh-duong/'
    | '/dinh-duong/template/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cong-nghe'
    | '/duong-sinh'
    | '/ke-don'
    | '/kham-benh'
    | '/mo-phong'
    | '/vong-chan'
    | '/dinh-duong/benh-an'
    | '/dinh-duong'
    | '/dinh-duong/template/$slug'
  id:
    | '__root__'
    | '/'
    | '/cong-nghe'
    | '/duong-sinh'
    | '/ke-don'
    | '/kham-benh'
    | '/mo-phong'
    | '/vong-chan'
    | '/dinh-duong/benh-an'
    | '/dinh-duong/'
    | '/dinh-duong/template/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CongNgheRoute: typeof CongNgheRoute
  DuongSinhRoute: typeof DuongSinhRoute
  KeDonRoute: typeof KeDonRoute
  KhamBenhRoute: typeof KhamBenhRoute
  MoPhongRoute: typeof MoPhongRoute
  VongChanRoute: typeof VongChanRoute
  DinhDuongBenhAnRoute: typeof DinhDuongBenhAnRoute
  DinhDuongIndexRoute: typeof DinhDuongIndexRoute
  DinhDuongTemplateSlugRoute: typeof DinhDuongTemplateSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vong-chan': {
      id: '/vong-chan'
      path: '/vong-chan'
      fullPath: '/vong-chan'
      preLoaderRoute: typeof VongChanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mo-phong': {
      id: '/mo-phong'
      path: '/mo-phong'
      fullPath: '/mo-phong'
      preLoaderRoute: typeof MoPhongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kham-benh': {
      id: '/kham-benh'
      path: '/kham-benh'
      fullPath: '/kham-benh'
      preLoaderRoute: typeof KhamBenhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ke-don': {
      id: '/ke-don'
      path: '/ke-don'
      fullPath: '/ke-don'
      preLoaderRoute: typeof KeDonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duong-sinh': {
      id: '/duong-sinh'
      path: '/duong-sinh'
      fullPath: '/duong-sinh'
      preLoaderRoute: typeof DuongSinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-nghe': {
      id: '/cong-nghe'
      path: '/cong-nghe'
      fullPath: '/cong-nghe'
      preLoaderRoute: typeof CongNgheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinh-duong/': {
      id: '/dinh-duong/'
      path: '/dinh-duong'
      fullPath: '/dinh-duong/'
      preLoaderRoute: typeof DinhDuongIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinh-duong/benh-an': {
      id: '/dinh-duong/benh-an'
      path: '/dinh-duong/benh-an'
      fullPath: '/dinh-duong/benh-an'
      preLoaderRoute: typeof DinhDuongBenhAnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinh-duong/template/$slug': {
      id: '/dinh-duong/template/$slug'
      path: '/dinh-duong/template/$slug'
      fullPath: '/dinh-duong/template/$slug'
      preLoaderRoute: typeof DinhDuongTemplateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CongNgheRoute: CongNgheRoute,
  DuongSinhRoute: DuongSinhRoute,
  KeDonRoute: KeDonRoute,
  KhamBenhRoute: KhamBenhRoute,
  MoPhongRoute: MoPhongRoute,
  VongChanRoute: VongChanRoute,
  DinhDuongBenhAnRoute: DinhDuongBenhAnRoute,
  DinhDuongIndexRoute: DinhDuongIndexRoute,
  DinhDuongTemplateSlugRoute: DinhDuongTemplateSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
